apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reliabilityhub
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - reliabilityhub-deployment.yaml
  - alert-router-deployment.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - grafana.yaml
